---
title: "Server Actionでのエラーを処理したい場合"
---

:::message
- 確認に使用したNext.jsのバージョン: v15.5.6
- 確認に使用したリポジトリー: https://github.com/makotot/next-render-cookbook-server-action-error-handling
:::



Server Actionでは、サーバー環境で処理が実行されますがその処理中にエラーが発生することは多分にあり、そのエラーをどのように扱うかはよくある実装上の課題でしょう。

Next.jsの公式ドキュメントでは、[エラーハンドリング](https://nextjs.org/docs/app/getting-started/error-handling)についてのページが用意されており、基本的なエラーハンドリングの方法が説明されています。

> Errors can be divided into two categories: expected errors and uncaught exceptions

文中には上述のようにあり、エラーは「予期されたエラー」と「予期されない例外」に分けられると説明されています。これは全体に共通した分類ですが、Server Actionも例外ではないでしょう。

## 予期されたエラー

多くのケースは、予期されたエラーに該当するでしょう。例えば、データベースへの保存に失敗した場合やユーザーの権限に問題がある場合など、アプリケーションの通常のフローの中で発生しうるエラーです。
「expected errors（予期されたエラー）」とは何を指すのかというと、アプリケーションのUIにおいてサーバーアクションの呼び出し元でサーバーアクションから返された値をもとにUIを制御したいエラーを指すと言えそうです。

> You can use the [useActionState](https://react.dev/reference/react/useActionState) hook to handle expected errors in Server Functions.
> For these errors, avoid using try/catch blocks and throw errors. Instead, model expected errors as return values.

[Next.js公式ドキュメント](https://nextjs.org/docs/app/getting-started/error-handling#server-functions)では、上述のように説明されていて、返り値としてエラーをモデル化することが推奨されています。
例外を投げるのではなく、返り値としてエラー情報を返すことで、呼び出し元でその情報を受け取りUIに反映させることができます。
具体的には、以下のようなコード例が考えられます。

```tsx
'use server';
import { revalidatePath } from 'next/cache';

export async function createPostAction(data: FormData) {
  const content = data.get('content');

  const result = await db.post.create({ content });

  if (!result) {
    // 予期されたエラーとして処理
    return {
      success: false,
      message: 'Failed to create post',
    }
  }

  revalidatePath('/posts');

  return {
    success: true,
    message: 'Post created successfully',
  }
}
```

上記のコード例では、`createPostAction`関数内において予期されたエラーの場合にエラーメッセージを含むオブジェクトを返します。これにより、呼び出し元のUIコンポーネントでこの結果を受け取り、適切なフィードバックをユーザーに提供できます。

Server Actionの状態を管理し、UIに反映させることができる[`useActionState`](https://ja.react.dev/reference/react/useActionState) フックにより、上記のようなエラーハンドリングが容易になります。

```tsx
'use client';
import { useActionState } from 'react';
import { createPostAction } from './actions';

export function PostForm() {
  const [state, formAction, pending] = useActionState(createPostAction);
  
  return (
    <form action={formAction}>
      <textarea name="content" required />
      {state && !state.success && (
        <p style={{ color: 'red' }}>{state.message}</p>
      )}
      <button type="submit" disabled={pending}>
        {pending ? 'Creating...' : 'Create Post'}
      </button>
    </form>
  );
}
```

## 予期されないエラー

一方で、予期されない例外は、通常のアプリケーションのフローでは発生しないエラーを指します。サーバーアクションにおいて値を返さずに例外をスローする場合、[エラーバウンダリーへフォールバック](https://nextjs.org/docs/app/getting-started/error-handling#handling-uncaught-exceptions)します。
ただ、基本的に値としてエラーを返すことで対処でき、エラーバウンダリーへフォールバックするUIが望ましいケースはあまり無いと思われるので、サーバーアクションから予期されない例外をスローするケースは少ないと考えられます。